package com.demo.listen.net

object PinyinHanziMap {
    private val map: Map<String, String> = mapOf(
        // b
        "bā" to "巴", "bá" to "拔", "bǎ" to "把", "bà" to "爸",
        "bō" to "波", "bó" to "伯", "bǒ" to "跛", "bò" to "薄",
        "bī" to "逼", "bí" to "鼻", "bǐ" to "笔", "bì" to "必",
        "bū" to "逋", "bú" to "醭", "bǔ" to "补", "bù" to "不",
        "bāi" to "掰", "bái" to "白", "bǎi" to "百", "bài" to "败",
        "bēi" to "杯", "běi" to "北", "bèi" to "被",
        "bāo" to "包", "báo" to "薄", "bǎo" to "宝", "bào" to "报",
        "bān" to "班", "bǎn" to "板", "bàn" to "半",
        "bēn" to "奔", "běn" to "本", "bèn" to "笨",
        "bāng" to "帮", "bǎng" to "绑", "bàng" to "棒",
        "bēng" to "崩", "béng" to "甭", "běng" to "绷", "bèng" to "蹦",
        "biān" to "边", "biǎn" to "扁", "biàn" to "变",
        "biāo" to "标", "biáo" to "嫖", "biǎo" to "表", "biào" to "鳔",
        "biē" to "憋", "bié" to "别", "biě" to "瘪", "biè" to "别",
        "bīn" to "宾", "bǐn" to "殡", "bìn" to "鬓",
        "bīng" to "冰", "bǐng" to "饼", "bìng" to "病",
        // p
        "pā" to "趴", "pá" to "爬", "pà" to "怕",
        "pō" to "坡", "pó" to "婆", "pǒ" to "叵", "pò" to "破",
        "pī" to "批", "pí" to "皮", "pǐ" to "匹", "pì" to "屁",
        "pū" to "扑", "pú" to "葡", "pǔ" to "普", "pù" to "瀑",
        "pāi" to "拍", "pái" to "排", "pǎi" to "迫", "pài" to "派",
        "pēi" to "胚", "péi" to "陪", "pěi" to "培", "pèi" to "配",
        "pāo" to "抛", "páo" to "袍", "pǎo" to "跑", "pào" to "炮",
        "pōu" to "剖", "póu" to "抔", "pǒu" to "掊", "pòu" to "椟",
        "pān" to "攀", "pán" to "盘", "pǎn" to "判", "pàn" to "盼",
        "pēn" to "喷", "pén" to "盆", "pěn" to "喷", "pèn" to "喷",
        "pāng" to "乓", "páng" to "旁", "pǎng" to "耪", "pàng" to "胖",
        "pēng" to "烹", "péng" to "朋", "pěng" to "捧", "pèng" to "碰",
        "piān" to "篇", "pián" to "便", "piǎn" to "谝", "piàn" to "片",
        "piāo" to "飘", "piáo" to "瓢", "piǎo" to "漂", "piào" to "票",
        "piē" to "瞥", "piě" to "撇", "piè" to "丿",
        "pīn" to "拼", "pín" to "贫", "pǐn" to "品", "pìn" to "聘",
        "pīng" to "乒", "píng" to "平", "pìng" to "牝",
        // m
        "mā" to "妈", "má" to "麻", "mǎ" to "马", "mà" to "骂",
        "mō" to "摸", "mó" to "模", "mǒ" to "抹", "mò" to "末",
        "mī" to "咪", "mí" to "迷", "mǐ" to "米", "mì" to "蜜",
        "mū" to "母", "mú" to "模", "mǔ" to "母", "mù" to "木",
        "māi" to "埋", "mǎi" to "买", "mài" to "卖",
        "méi" to "没", "měi" to "美", "mèi" to "妹",
        "māo" to "猫", "máo" to "毛", "mǎo" to "卯", "mào" to "冒",
        "mōu" to "哞", "móu" to "谋", "mǒu" to "某", "mòu" to "缪",
        "mān" to "颟", "mán" to "蛮", "mǎn" to "满", "màn" to "慢",
        "mēn" to "闷", "mén" to "门", "měn" to "们", "mèn" to "闷",
        "māng" to "忙", "máng" to "盲", "mǎng" to "莽", "màng" to "蟒",
        "mēng" to "蒙", "méng" to "盟", "měng" to "猛", "mèng" to "梦",
        "miān" to "棉", "mián" to "眠", "miǎn" to "免", "miàn" to "面",
        "miāo" to "喵", "miáo" to "苗", "miǎo" to "秒", "miào" to "妙",
        "miē" to "咩", "mié" to "乜", "miè" to "灭",
        "mín" to "民", "mǐn" to "敏", "mìn" to "闽",
        "míng" to "明", "mǐng" to "酩", "mìng" to "命",
        "miū" to "谬", "miú" to "缪", "miǔ" to "拗", "miù" to "谬",
        // f
        "fā" to "发", "fá" to "罚", "fǎ" to "法", "fà" to "发",
        "fō" to "佛", "fó" to "佛", "fǒ" to "", "fò" to "",
        "fū" to "夫", "fú" to "福", "fǔ" to "府", "fù" to "父",
        "fēi" to "飞", "féi" to "肥", "fěi" to "匪", "fèi" to "费",
        "fōu" to "否", "fóu" to "", "fǒu" to "否", "fòu" to "",
        "fān" to "翻", "fán" to "凡", "fǎn" to "反", "fàn" to "饭",
        "fēn" to "分", "fén" to "坟", "fěn" to "粉", "fèn" to "份",
        "fāng" to "方", "fáng" to "房", "fǎng" to "访", "fàng" to "放",
        "fēng" to "风", "féng" to "逢", "fěng" to "讽", "fèng" to "凤",
        // d
        "dā" to "搭", "dá" to "达", "dǎ" to "打", "dà" to "大",
        "dē" to "得", "dé" to "德", "dě" to "", "dè" to "",
        "dī" to "低", "dí" to "敌", "dǐ" to "底", "dì" to "地",
        "dū" to "都", "dú" to "读", "dǔ" to "堵", "dù" to "度",
        "dāi" to "呆", "dǎi" to "歹", "dài" to "带",
        "dēi" to "得", "děi" to "得", "dèi" to "",
        "dāo" to "刀", "dáo" to "", "dǎo" to "倒", "dào" to "到",
        "dōu" to "都", "dǒu" to "抖", "dòu" to "豆",
        "dān" to "单", "dán" to "", "dǎn" to "胆", "dàn" to "蛋",
        "dēn" to "", "dén" to "", "děn" to "", "dèn" to "",
        "dāng" to "当", "dáng" to "", "dǎng" to "党", "dàng" to "荡",
        "dēng" to "灯", "déng" to "", "děng" to "等", "dèng" to "邓",
        "dōng" to "东", "dóng" to "", "dǒng" to "懂", "dòng" to "动",
        "diān" to "颠", "dián" to "", "diǎn" to "点", "diàn" to "电",
        "diāo" to "雕", "diáo" to "", "diǎo" to "鸟", "diào" to "掉",
        "diē" to "跌", "dié" to "蝶", "diě" to "", "diè" to "",
        "diū" to "丢", "diú" to "", "diǔ" to "", "diù" to "",
        "dīng" to "丁", "díng" to "", "dǐng" to "顶", "dìng" to "定",
        "duō" to "多", "duó" to "夺", "duǒ" to "朵", "duò" to "舵",
        "duān" to "端", "duán" to "", "duǎn" to "短", "duàn" to "段",
        "dūn" to "蹲", "dún" to "", "dǔn" to "盾", "dùn" to "顿",
        // t
        "tā" to "他", "tá" to "塔", "tǎ" to "塔", "tà" to "踏",
        "tē" to "", "té" to "", "tě" to "", "tè" to "特",
        "tī" to "梯", "tí" to "题", "tǐ" to "体", "tì" to "替",
        "tū" to "突", "tú" to "图", "tǔ" to "土", "tù" to "兔",
        "tāi" to "胎", "tái" to "台", "tǎi" to "", "tài" to "太",
        "tāo" to "掏", "táo" to "桃", "tǎo" to "讨", "tào" to "套",
        "tōu" to "偷", "tóu" to "头", "tǒu" to "", "tòu" to "透",
        "tān" to "摊", "tán" to "谈", "tǎn" to "坦", "tàn" to "叹",
        "tēn" to "", "tén" to "", "těn" to "", "tèn" to "",
        "tāng" to "汤", "táng" to "唐", "tǎng" to "躺", "tàng" to "烫",
        "tēng" to "", "téng" to "腾", "těng" to "", "tèng" to "",
        "tōng" to "通", "tóng" to "同", "tǒng" to "统", "tòng" to "痛",
        "tiān" to "天", "tián" to "田", "tiǎn" to "舔", "tiàn" to "",
        "tiāo" to "挑", "tiáo" to "条", "tiǎo" to "挑", "tiào" to "跳",
        "tiē" to "贴", "tié" to "", "tiě" to "铁", "tiè" to "帖",
        "tīng" to "听", "tíng" to "停", "tǐng" to "挺", "tìng" to "听",
        "tuō" to "拖", "tuó" to "驼", "tuǒ" to "妥", "tuò" to "拓",
        "tuān" to "", "tuán" to "团", "tuǎn" to "", "tuàn" to "",
        "tūn" to "吞", "tún" to "屯", "tǔn" to "", "tùn" to "褪",
        // n
        "nā" to "那", "ná" to "拿", "nǎ" to "哪", "nà" to "那",
        "nē" to "", "né" to "", "ně" to "", "nè" to "讷",
        "nī" to "妮", "ní" to "泥", "nǐ" to "你", "nì" to "逆",
        "nū" to "", "nú" to "奴", "nǔ" to "努", "nù" to "怒",
        "nü" to "", "nǘ" to "", "nǚ" to "女", "nǜ" to "趣",
        "nāi" to "", "nái" to "", "nǎi" to "奶", "nài" to "耐",
        "nēi" to "", "néi" to "", "něi" to "馁", "nèi" to "内",
        "nāo" to "", "náo" to "挠", "nǎo" to "脑", "nào" to "闹",
        "nōu" to "", "nóu" to "", "nǒu" to "", "nòu" to "",
        "nān" to "", "nán" to "难", "nǎn" to "赧", "nàn" to "难",
        "nēn" to "", "nén" to "", "něn" to "", "nèn" to "嫩",
        "nāng" to "", "náng" to "", "nǎng" to "", "nàng" to "",
        "nēng" to "", "néng" to "能", "něng" to "", "nèng" to "",
        "niān" to "拈", "nián" to "年", "niǎn" to "碾", "niàn" to "念",
        "niāo" to "", "niáo" to "", "niǎo" to "鸟", "niào" to "尿",
        "niē" to "捏", "nié" to "", "niě" to "", "niè" to "聂",
        "nīn" to "", "nín" to "您", "nǐn" to "", "nìn" to "",
        "niāng" to "", "niáng" to "娘", "niǎng" to "", "niàng" to "酿",
        "niē" to "", "nié" to "", "niě" to "", "niè" to "",
        "nīng" to "宁", "níng" to "凝", "nǐng" to "拧", "nìng" to "宁",
        "nuō" to "", "nuó" to "挪", "nuǒ" to "", "nuò" to "诺",
        "nuān" to "", "nuán" to "", "nuǎn" to "暖", "nuàn" to "",
        "nūn" to "", "nún" to "", "nǔn" to "", "nùn" to "",
        "nüè" to "虐",
        // l
        "lā" to "拉", "lá" to "蜡", "lǎ" to "喇", "là" to "辣",
        "lē" to "", "lé" to "", "lě" to "", "lè" to "乐",
        "lī" to "", "lí" to "离", "lǐ" to "里", "lì" to "力",
        "lū" to "", "lú" to "炉", "lǔ" to "鲁", "lù" to "路",
        "lü" to "", "lǘ" to "驴", "lǚ" to "旅", "lǜ" to "绿",
        "lāi" to "", "lái" to "来", "lǎi" to "", "lài" to "赖",
        "lēi" to "", "léi" to "雷", "lěi" to "累", "lèi" to "类",
        "lāo" to "捞", "láo" to "劳", "lǎo" to "老", "lào" to "涝",
        "lōu" to "搂", "lóu" to "楼", "lǒu" to "搂", "lòu" to "漏",
        "lān" to "", "lán" to "蓝", "lǎn" to "懒", "làn" to "烂",
        "lēn" to "", "lén" to "", "lěn" to "", "lèn" to "",
        "lāng" to "郎", "láng" to "狼", "lǎng" to "朗", "làng" to "浪",
        "lēng" to "", "léng" to "棱", "lěng" to "冷", "lèng" to "愣",
        "liā" to "", "liá" to "", "liǎ" to "俩", "lià" to "",
        "liān" to "", "lián" to "连", "liǎn" to "脸", "liàn" to "练",
        "liāo" to "", "liáo" to "聊", "liǎo" to "了", "liào" to "料",
        "liē" to "", "lié" to "", "liě" to "咧", "liè" to "列",
        "liū" to "溜", "liú" to "流", "liǔ" to "柳", "liù" to "六",
        "līng" to "令", "líng" to "灵", "lǐng" to "领", "lìng" to "令",
        "luō" to "", "luó" to "罗", "luǒ" to "裸", "luò" to "落",
        "luān" to "", "luán" to "峦", "luǎn" to "卵", "luàn" to "乱",
        "lūn" to "抡", "lún" to "轮", "lǔn" to "", "lùn" to "论",
        "lüè" to "略",
        // g
        "gā" to "嘎", "gá" to "", "gǎ" to "尕", "gà" to "尬",
        "gē" to "哥", "gé" to "格", "gě" to "葛", "gè" to "个",
        "gū" to "姑", "gú" to "", "gǔ" to "古", "gù" to "故",
        "gāi" to "该", "gái" to "", "gǎi" to "改", "gài" to "盖",
        "gěi" to "给",
        "gāo" to "高", "gáo" to "", "gǎo" to "搞", "gào" to "告",
        "gōu" to "沟", "góu" to "", "gǒu" to "狗", "gòu" to "够",
        "gān" to "干", "gán" to "", "gǎn" to "敢", "gàn" to "干",
        "gēn" to "根", "gén" to "", "gěn" to "", "gèn" to "亘",
        "gāng" to "刚", "gáng" to "", "gǎng" to "港", "gàng" to "杠",
        "gēng" to "更", "géng" to "", "gěng" to "梗", "gèng" to "更",
        "gōng" to "工", "góng" to "", "gǒng" to "拱", "gòng" to "共",
        "guā" to "瓜", "guá" to "", "guǎ" to "寡", "guà" to "挂",
        "guāi" to "乖", "guái" to "", "guǎi" to "拐", "guài" to "怪",
        "guān" to "关", "guán" to "", "guǎn" to "管", "guàn" to "惯",
        "guāng" to "光", "guáng" to "", "guǎng" to "广", "guàng" to "",
        "guī" to "归", "guí" to "回", "guǐ" to "鬼", "guì" to "贵",
        "gūn" to "滚", "gún" to "", "gǔn" to "滚", "gùn" to "",
        "guō" to "锅", "guó" to "国", "guǒ" to "果", "guò" to "过",
        // k
        "kā" to "卡", "ká" to "", "kǎ" to "卡", "kà" to "",
        "kē" to "科", "ké" to "壳", "kě" to "可", "kè" to "客",
        "kū" to "哭", "kú" to "", "kǔ" to "苦", "kù" to "裤",
        "kāi" to "开", "kái" to "", "kǎi" to "凯", "kài" to "",
        "kěi" to "",
        "kāo" to "", "káo" to "", "kǎo" to "考", "kào" to "靠",
        "kōu" to "", "kóu" to "", "kǒu" to "口", "kòu" to "扣",
        "kān" to "刊", "kán" to "", "kǎn" to "砍", "kàn" to "看",
        "kēn" to "", "kén" to "", "kěn" to "肯", "kèn" to "",
        "kāng" to "康", "káng" to "", "kǎng" to "慷", "kàng" to "抗",
        "kēng" to "坑", "kéng" to "", "kěng" to "", "kèng" to "",
        "kōng" to "空", "kóng" to "", "kǒng" to "孔", "kòng" to "空",
        "kuā" to "夸", "kuá" to "", "kuǎ" to "垮", "kuà" to "跨",
        "kuāi" to "", "kuái" to "", "kuǎi" to "揣", "kuài" to "快",
        "kuān" to "宽", "kuán" to "", "kuǎn" to "款", "kuàn" to "",
        "kuāng" to "", "kuáng" to "狂", "kuǎng" to "", "kuàng" to "况",
        "kuī" to "亏", "kuí" to "葵", "kuǐ" to "傀", "kuì" to "愧",
        "kūn" to "昆", "kún" to "", "kǔn" to "捆", "kùn" to "困",
        "kuō" to "", "kuó" to "", "kuǒ" to "", "kuò" to "阔",
        // h
        "hā" to "哈", "há" to "", "hǎ" to "哈", "hà" to "",
        "hē" to "喝", "hé" to "和", "hě" to "", "hè" to "贺",
        "hū" to "呼", "hú" to "胡", "hǔ" to "虎", "hù" to "户",
        "hāi" to "嗨", "hái" to "还", "hǎi" to "海", "hài" to "害",
        "hēi" to "黑", "héi" to "", "hěi" to "", "hèi" to "",
        "hāo" to "蒿", "háo" to "豪", "hǎo" to "好", "hào" to "号",
        "hōu" to "", "hóu" to "猴", "hǒu" to "吼", "hòu" to "后",
        "hān" to "酣", "hán" to "寒", "hǎn" to "喊", "hàn" to "汉",
        "hēn" to "", "hén" to "痕", "hěn" to "很", "hèn" to "恨",
        "hāng" to "", "háng" to "行", "hǎng" to "", "hàng" to "巷",
        "hēng" to "哼", "héng" to "恒", "hěng" to "", "hèng" to "横",
        "hōng" to "轰", "hóng" to "红", "hǒng" to "哄", "hòng" to "哄",
        "huā" to "花", "huá" to "华", "huǎ" to "", "huà" to "画",
        "huāi" to "坏", "huái" to "怀", "huǎi" to "", "huài" to "坏",
        "huān" to "欢", "huán" to "还", "huǎn" to "缓", "huàn" to "换",
        "huāng" to "荒", "huáng" to "黄", "huǎng" to "谎", "huàng" to "晃",
        "huī" to "灰", "huí" to "回", "huǐ" to "毁", "huì" to "会",
        "hūn" to "昏", "hún" to "魂", "hǔn" to "", "hùn" to "混",
        "huō" to "豁", "huó" to "活", "huǒ" to "火", "huò" to "货",
        // j
        "jī" to "机", "jí" to "极", "jǐ" to "几", "jì" to "记",
        "jū" to "居", "jú" to "局", "jǔ" to "举", "jù" to "句",
        "jiā" to "家", "jiá" to "", "jiǎ" to "假", "jià" to "价",
        "jiāo" to "交", "jiáo" to "嚼", "jiǎo" to "角", "jiào" to "叫",
        "jiē" to "街", "jié" to "节", "jiě" to "解", "jiè" to "借",
        "jiū" to "究", "jiú" to "", "jiǔ" to "九", "jiù" to "就",
        "jiān" to "间", "jián" to "", "jiǎn" to "简", "jiàn" to "见",
        "jīn" to "今", "jín" to "", "jǐn" to "紧", "jìn" to "进",
        "jiāng" to "江", "jiáng" to "", "jiǎng" to "讲", "jiàng" to "将",
        "jīng" to "京", "jíng" to "", "jǐng" to "景", "jìng" to "静",
        "jiōng" to "", "jióng" to "", "jiǒng" to "窘", "jiòng" to "",
        "juē" to "撅", "jué" to "决", "juě" to "", "juè" to "倔",
        "juān" to "捐", "juán" to "", "juǎn" to "卷", "juàn" to "倦",
        "jūn" to "军", "jún" to "", "jǔn" to "", "jùn" to "俊",
        // q
        "qī" to "七", "qí" to "齐", "qǐ" to "起", "qì" to "气",
        "qū" to "区", "qú" to "渠", "qǔ" to "取", "qù" to "去",
        "qiā" to "", "qiá" to "", "qiǎ" to "卡", "qià" to "恰",
        "qiāo" to "敲", "qiáo" to "桥", "qiǎo" to "巧", "qiào" to "俏",
        "qiē" to "切", "qié" to "茄", "qiě" to "且", "qiè" to "切",
        "qiū" to "秋", "qiú" to "求", "qiǔ" to "", "qiù" to "",
        "qiān" to "千", "qián" to "前", "qiǎn" to "浅", "qiàn" to "欠",
        "qīn" to "亲", "qín" to "琴", "qǐn" to "寝", "qìn" to "沁",
        "qiāng" to "枪", "qiáng" to "强", "qiǎng" to "抢", "qiàng" to "呛",
        "qīng" to "青", "qíng" to "情", "qǐng" to "请", "qìng" to "庆",
        "qiōng" to "", "qióng" to "穷", "qiǒng" to "", "qiòng" to "",
        "quē" to "缺", "qué" to "", "quě" to "", "què" to "确",
        "quān" to "圈", "quán" to "全", "quǎn" to "犬", "quàn" to "劝",
        "qūn" to "", "qún" to "群", "qǔn" to "", "qùn" to "",
        // x
        "xī" to "西", "xí" to "习", "xǐ" to "洗", "xì" to "细",
        "xū" to "虚", "xú" to "", "xǔ" to "许", "xù" to "续",
        "xiā" to "虾", "xiá" to "霞", "xiǎ" to "", "xià" to "下",
        "xiāo" to "消", "xiáo" to "", "xiǎo" to "小", "xiào" to "笑",
        "xiē" to "些", "xié" to "鞋", "xiě" to "写", "xiè" to "谢",
        "xiū" to "修", "xiú" to "", "xiǔ" to "朽", "xiù" to "秀",
        "xiān" to "先", "xián" to "闲", "xiǎn" to "显", "xiàn" to "现",
        "xīn" to "新", "xín" to "", "xǐn" to "", "xìn" to "信",
        "xiāng" to "香", "xiáng" to "祥", "xiǎng" to "想", "xiàng" to "向",
        "xīng" to "星", "xíng" to "行", "xǐng" to "醒", "xìng" to "幸",
        "xiōng" to "凶", "xióng" to "雄", "xiǒng" to "", "xiòng" to "",
        "xuē" to "削", "xué" to "学", "xuě" to "雪", "xuè" to "血",
        "xuān" to "宣", "xuán" to "旋", "xuǎn" to "选", "xuàn" to "炫",
        "xūn" to "勋", "xún" to "寻", "xǔn" to "", "xùn" to "训",
        // zh
        "zhā" to "扎", "zhá" to "闸", "zhǎ" to "眨", "zhà" to "炸",
        "zhē" to "遮", "zhé" to "折", "zhě" to "者", "zhè" to "这",
        "zhī" to "知", "zhí" to "直", "zhǐ" to "指", "zhì" to "志",
        "zhū" to "猪", "zhú" to "竹", "zhǔ" to "主", "zhù" to "住",
        "zhāi" to "摘", "zhái" to "宅", "zhǎi" to "窄", "zhài" to "债",
        "zhēi" to "", "zhéi" to "", "zhěi" to "", "zhèi" to "",
        "zhāo" to "招", "zháo" to "着", "zhǎo" to "找", "zhào" to "照",
        "zhōu" to "周", "zhóu" to "轴", "zhǒu" to "肘", "zhòu" to "宙",
        "zhān" to "沾", "zhán" to "", "zhǎn" to "展", "zhàn" to "战",
        "zhēn" to "真", "zhén" to "", "zhěn" to "诊", "zhèn" to "镇",
        "zhāng" to "张", "zháng" to "", "zhǎng" to "长", "zhàng" to "丈",
        "zhēng" to "争", "zhéng" to "正", "zhěng" to "整", "zhèng" to "正",
        "zhōng" to "中", "zhóng" to "", "zhǒng" to "种", "zhòng" to "重",
        "zhuā" to "抓", "zhuá" to "", "zhuǎ" to "爪", "zhuà" to "",
        "zhuāi" to "", "zhuái" to "", "zhuǎi" to "拽", "zhuài" to "拽",
        "zhuān" to "专", "zhuán" to "", "zhuǎn" to "转", "zhuàn" to "传",
        "zhuāng" to "庄", "zhuáng" to "", "zhuǎng" to "", "zhuàng" to "壮",
        "zhuī" to "追", "zhuí" to "", "zhuǐ" to "", "zhuì" to "坠",
        "zhūn" to "准", "zhún" to "", "zhǔn" to "准", "zhùn" to "",
        "zhuō" to "桌", "zhuó" to "着", "zhuǒ" to "", "zhuò" to "拙",
        // ch
        "chā" to "插", "chá" to "查", "chǎ" to "", "chà" to "差",
        "chē" to "车", "ché" to "", "chě" to "", "chè" to "彻",
        "chī" to "吃", "chí" to "迟", "chǐ" to "尺", "chì" to "翅",
        "chū" to "出", "chú" to "除", "chǔ" to "处", "chù" to "处",
        "chāi" to "拆", "chái" to "柴", "chǎi" to "", "chài" to "",
        "chāo" to "超", "cháo" to "朝", "chǎo" to "吵", "chào" to "潮",
        "chōu" to "抽", "chóu" to "愁", "chǒu" to "丑", "chòu" to "臭",
        "chān" to "掺", "chán" to "缠", "chǎn" to "产", "chàn" to "颤",
        "chēn" to "嗔", "chén" to "尘", "chěn" to "", "chèn" to "衬",
        "chāng" to "昌", "cháng" to "长", "chǎng" to "厂", "chàng" to "唱",
        "chēng" to "称", "chéng" to "成", "chěng" to "逞", "chèng" to "",
        "chōng" to "冲", "chóng" to "虫", "chǒng" to "宠", "chòng" to "冲",
        "chuā" to "", "chuá" to "", "chuǎ" to "", "chuà" to "",
        "chuāi" to "揣", "chuái" to "", "chuǎi" to "揣", "chuài" to "踹",
        "chuān" to "穿", "chuán" to "传", "chuǎn" to "喘", "chuàn" to "串",
        "chuāng" to "窗", "chuáng" to "床", "chuǎng" to "闯", "chuàng" to "创",
        "chuī" to "吹", "chuí" to "垂", "chuǐ" to "", "chuì" to "",
        "chūn" to "春", "chún" to "纯", "chǔn" to "蠢", "chùn" to "",
        "chuō" to "戳", "chuó" to "", "chuǒ" to "", "chuò" to "绰",
        // sh
        "shā" to "沙", "shá" to "", "shǎ" to "傻", "shà" to "厦",
        "shē" to "奢", "shé" to "蛇", "shě" to "舍", "shè" to "社",
        "shī" to "师", "shí" to "十", "shǐ" to "史", "shì" to "是",
        "shū" to "书", "shú" to "熟", "shǔ" to "属", "shù" to "树",
        "shāi" to "筛", "shái" to "", "shǎi" to "", "shài" to "晒",
        "shēi" to "", "shéi" to "谁", "shěi" to "", "shèi" to "",
        "shāo" to "烧", "sháo" to "勺", "shǎo" to "少", "shào" to "哨",
        "shōu" to "收", "shóu" to "", "shǒu" to "手", "shòu" to "受",
        "shān" to "山", "shán" to "", "shǎn" to "闪", "shàn" to "善",
        "shēn" to "身", "shén" to "神", "shěn" to "审", "shèn" to "慎",
        "shāng" to "伤", "sháng" to "", "shǎng" to "赏", "shàng" to "上",
        "shēng" to "生", "shéng" to "绳", "shěng" to "省", "shèng" to "胜",
        "shuā" to "刷", "shuá" to "", "shuǎ" to "耍", "shuà" to "",
        "shuāi" to "摔", "shuái" to "", "shuǎi" to "甩", "shuài" to "帅",
        "shuān" to "拴", "shuán" to "", "shuǎn" to "", "shuàn" to "涮",
        "shuāng" to "双", "shuáng" to "", "shuǎng" to "爽", "shuàng" to "",
        "shuī" to "", "shuí" to "谁", "shuǐ" to "水", "shuì" to "睡",
        "shūn" to "吮", "shún" to "", "shǔn" to "吮", "shùn" to "顺",
        "shuō" to "说", "shuó" to "", "shuǒ" to "", "shuò" to "硕",
        // r
        "rē" to "", "ré" to "", "rě" to "惹", "rè" to "热",
        "rī" to "", "rí" to "", "rǐ" to "", "rì" to "日",
        "rū" to "", "rú" to "如", "rǔ" to "乳", "rù" to "入",
        "rāo" to "", "ráo" to "饶", "rǎo" to "扰", "rào" to "绕",
        "rōu" to "", "róu" to "柔", "rǒu" to "", "ròu" to "肉",
        "rān" to "", "rán" to "然", "rǎn" to "染", "ràn" to "",
        "rēn" to "", "rén" to "人", "rěn" to "忍", "rèn" to "任",
        "rāng" to "", "ráng" to "嚷", "rǎng" to "壤", "ràng" to "让",
        "rēng" to "扔", "réng" to "仍", "rěng" to "", "rèng" to "",
        "rōng" to "", "róng" to "荣", "rǒng" to "冗", "ròng" to "",
        "ruā" to "", "ruá" to "", "ruǎ" to "", "ruà" to "",
        "ruān" to "", "ruán" to "", "ruǎn" to "软", "ruàn" to "",
        "ruī" to "", "ruí" to "", "ruǐ" to "蕊", "ruì" to "锐",
        "rūn" to "", "rún" to "", "rǔn" to "", "rùn" to "润",
        "ruō" to "", "ruó" to "", "ruǒ" to "若", "ruò" to "弱",
        // z
        "zā" to "扎", "zá" to "杂", "zǎ" to "", "zà" to "",
        "zē" to "", "zé" to "责", "zě" to "", "zè" to "",
        "zī" to "资", "zí" to "", "zǐ" to "子", "zì" to "自",
        "zū" to "租", "zú" to "足", "zǔ" to "组", "zù" to "",
        "zāi" to "栽", "zái" to "", "zǎi" to "仔", "zài" to "在",
        "zēi" to "贼", "zéi" to "贼", "zěi" to "", "zèi" to "",
        "zāo" to "遭", "záo" to "凿", "zǎo" to "早", "zào" to "造",
        "zōu" to "走", "zóu" to "", "zǒu" to "走", "zòu" to "奏",
        "zān" to "簪", "zán" to "咱", "zǎn" to "攒", "zàn" to "赞",
        "zēn" to "", "zén" to "", "zěn" to "怎", "zèn" to "",
        "zāng" to "脏", "záng" to "", "zǎng" to "", "zàng" to "葬",
        "zēng" to "增", "zéng" to "", "zěng" to "", "zèng" to "赠",
        "zōng" to "宗", "zóng" to "", "zǒng" to "总", "zòng" to "纵",
        "zuān" to "钻", "zuán" to "", "zuǎn" to "纂", "zuàn" to "钻",
        "zuī" to "嘴", "zuí" to "", "zuǐ" to "嘴", "zuì" to "最",
        "zūn" to "尊", "zún" to "", "zǔn" to "", "zùn" to "",
        "zuō" to "", "zuó" to "昨", "zuǒ" to "左", "zuò" to "做",
        // c
        "cā" to "擦", "cá" to "", "cǎ" to "", "cà" to "",
        "cē" to "", "cé" to "", "cě" to "", "cè" to "策",
        "cī" to "刺", "cí" to "词", "cǐ" to "此", "cì" to "次",
        "cū" to "粗", "cú" to "", "cǔ" to "", "cù" to "促",
        "cāi" to "猜", "cái" to "才", "cǎi" to "采", "cài" to "菜",
        "cāo" to "操", "cáo" to "曹", "cǎo" to "草", "cào" to "",
        "cōu" to "", "cóu" to "", "cǒu" to "", "còu" to "凑",
        "cān" to "参", "cán" to "残", "cǎn" to "惨", "càn" to "灿",
        "cēn" to "参", "cén" to "", "cěn" to "", "cèn" to "",
        "cāng" to "仓", "cáng" to "藏", "cǎng" to "", "càng" to "",
        "cēng" to "", "céng" to "层", "cěng" to "", "cèng" to "蹭",
        "cōng" to "聪", "cóng" to "从", "cǒng" to "", "còng" to "",
        "cuān" to "蹿", "cuán" to "攒", "cuǎn" to "", "cuàn" to "窜",
        "cuī" to "催", "cuí" to "", "cuǐ" to "璀", "cuì" to "翠",
        "cūn" to "村", "cún" to "存", "cǔn" to "", "cùn" to "寸",
        "cuō" to "搓", "cuó" to "", "cuǒ" to "", "cuò" to "错",
        // s
        "sā" to "撒", "sá" to "", "sǎ" to "洒", "sà" to "",
        "sē" to "", "sé" to "", "sě" to "", "sè" to "色",
        "sī" to "思", "sí" to "", "sǐ" to "死", "sì" to "四",
        "sū" to "苏", "sú" to "", "sǔ" to "", "sù" to "素",
        "sāi" to "塞", "sái" to "", "sǎi" to "", "sài" to "赛",
        "sāo" to "骚", "sáo" to "", "sǎo" to "扫", "sào" to "扫",
        "sōu" to "搜", "sóu" to "", "sǒu" to "叟", "sòu" to "嗽",
        "sān" to "三", "sán" to "", "sǎn" to "散", "sàn" to "散",
        "sēn" to "森", "sén" to "", "sěn" to "", "sèn" to "",
        "sāng" to "桑", "sáng" to "", "sǎng" to "嗓", "sàng" to "丧",
        "sēng" to "僧", "séng" to "", "sěng" to "", "sèng" to "",
        "sōng" to "松", "sóng" to "", "sǒng" to "耸", "sòng" to "送",
        "suān" to "酸", "suán" to "", "suǎn" to "", "suàn" to "算",
        "suī" to "虽", "suí" to "随", "suǐ" to "髓", "suì" to "岁",
        "sūn" to "孙", "sún" to "", "sǔn" to "损", "sùn" to "",
        "suō" to "缩", "suó" to "", "suǒ" to "锁", "suò" to ""
    )

    fun getHanzi(tonedPinyin: String): String? = map[tonedPinyin]
}
